import { createFileRoute } from '@tanstack/react-router'
export const Route = createFileRoute('/')({ component: Home })
import { ArrowUpRight, ArrowRight, Download } from "lucide-react";
const releaseReady = false;
const download = 'https://github.com/srikarsunchu/whop-desktop/releases/download/v0.4.0-preview.1/Whop-Desktop-0.4.0-Apple-Silicon.dmg';
const repo = 'https://github.com/srikarsunchu/whop-desktop';
export default function Home() {
  return <div className="site-shell">
    <header><a className="brand" href="#"><img src="/app-icon.png" alt="" width="32" height="32"/><span>Whop Desktop</span><span className="preview-label">Preview</span></a><nav><a href="#install">Install guide</a><a href={repo} className="icon-link">Source <ArrowUpRight className="link-icon" aria-hidden="true"/></a></nav></header>
    <main>
      <section className="hero"><div className="hero-kicker"><span/>UNOFFICIAL MAC APP</div><h1>Your Whop business.<br/><span>On your Mac.</span></h1><p className="hero-copy">Revenue, customers, creative work, and an assistant that pulls the numbers. One desktop workspace, built on the Whop CLI.</p><div className="hero-actions"><a className="download-button" href={releaseReady?download:"#demo"}>{releaseReady?"Download for Apple Silicon":"Watch the 17-second demo"} {releaseReady?<Download className="cta-icon" aria-hidden="true"/>:<ArrowRight className="cta-icon" aria-hidden="true"/>}</a><a className="watch-link" href={repo}>View the source <ArrowUpRight className="link-icon" aria-hidden="true"/></a></div><p className="download-note">Free preview · macOS 11+ · M1, M2, M3, M4 and newer Apple Silicon Macs</p><p className="preview-notice">The signed Mac preview is being prepared. <a href="#install">Read the install guide.</a></p></section>
      <section id="demo" className="demo-section" aria-label="Product demo"><div className="demo-topline"><span>A quick look inside</span></div><video controls playsInline muted preload="metadata" poster="/demo-poster.jpg" aria-label="Whop Desktop product demo"><source src="/demo.mp4" type="video/mp4"/>Your browser cannot play the video. <a href="/demo.mp4">Download the demo.</a></video><div className="demo-caption"><span>Built for the work between checking the numbers and deciding what’s next.</span><span>⌘K to get around</span></div></section>
      <section className="capabilities" aria-label="What you can try"><article><span>01 / UNDERSTAND</span><h2>See the business.</h2><p>Revenue, balances, members, and products together. Explore the populated demo before connecting your own account.</p></article><article><span>02 / ASK</span><h2>Get to the numbers.</h2><p>Ask the assistant about your business and see the commands behind its answer. Requires Claude Code installed and signed in.</p></article><article><span>03 / CREATE</span><h2>Make your next creative.</h2><p>Bring references into Studio, finish images with precise type, and carry the artwork and copy into a local ad draft.</p></article></section>
      <section id="install" className="install"><div className="install-intro"><span className="hero-kicker">GET STARTED</span><h2>Try it with a demo.<br/>Connect when you’re ready.</h2><p>The dashboards work without an account. Live business data uses your Whop CLI login. The assistant uses your Claude Code setup.</p><a href={releaseReady?download:`${repo}/releases`} className="text-download">{releaseReady?"Download the Mac preview":"Mac download coming soon · check releases"} {releaseReady?<Download className="link-icon" aria-hidden="true"/>:<ArrowUpRight className="link-icon" aria-hidden="true"/>}</a></div><ol><li><span className="step">1</span><div><h3>Download and install</h3><p>Open the DMG and drag Whop Desktop into Applications. This release is for Apple Silicon Macs; an Intel build is not included.</p></div></li><li><span className="step">2</span><div><h3>First launch on macOS</h3><p>Open Whop Desktop from Applications and confirm the standard macOS download prompt. The release will be signed with Developer ID and submitted to Apple for notarization before the download goes live.</p><a href="https://support.apple.com/102445" className="icon-link">Apple’s guidance for opening downloaded apps <ArrowUpRight className="link-icon" aria-hidden="true"/></a></div></li><li><span className="step">3</span><div><h3>Choose “Explore the demo”</h3><p>No login or payment needed to explore Northwind Picks. Its numbers are fictional, and Studio uses labeled samples. Connect your business from the welcome screen when you’re ready.</p></div></li></ol></section>
      <section className="release-note"><div><h2>A small, open-source experiment.</h2><p>I built this to explore what running a Whop business could feel like on the desktop. It’s an early preview, and feedback is welcome.</p></div><a href={`${repo}/issues`} className="icon-link">Report an issue <ArrowUpRight className="link-icon" aria-hidden="true"/></a></section>
    </main>
    <footer><div>Built by <a href="https://github.com/srikarsunchu">Srikar</a>. Unofficial. Not affiliated with or endorsed by Whop.</div><div><a href={`${repo}/releases`}>Releases</a><a href={repo} className="icon-link">GitHub <ArrowUpRight className="link-icon" aria-hidden="true"/></a></div></footer>
  </div>;
}
