import fs from 'node:fs';
import assert from 'node:assert/strict';
import ts from 'typescript';
import { execFileSync } from 'node:child_process';
const load = async path => {
 let source=fs.readFileSync(path,'utf8');
 if(path.endsWith('/demo.ts')) {
   const business=ts.transpileModule(fs.readFileSync('src/lib/business-demo.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
   source=source.replace('./business-demo','data:text/javascript;base64,'+Buffer.from(business).toString('base64'));
 }
 const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022}}).outputText;
 return import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
};
const {resolveMedia,mediaArgs,pendingMedia}=await load('src/lib/media.ts');
const {demoResolve}=await load('src/lib/demo.ts');
const base={id:'pending-test',type:'video',prompt:'Test',status:'processing',createdAt:Date.now(),accountId:'biz_test'};
let calls=0;
const file=async id=>{calls++;assert.equal(id,'file_test');return {id,url:'https://example.com/clip.mp4',content_type:'video/mp4',upload_status:'ready'};};
let g=await resolveMedia({id:'media_test',status:'completed',file:{id:'file_test'}},base,file);
assert.equal(g.status,'completed');assert.equal(g.url,'https://example.com/clip.mp4');assert.equal(calls,1);
g=await resolveMedia({data:{id:'media_test',status:'completed',file:{url:'https://example.com/clip.mp4',content_type:'video/mp4'}}},base,file);
assert.equal(g.status,'completed');assert.equal(calls,1,'URL already present: no redundant file fetch');
g=await resolveMedia({id:'media_test',status:'completed',file:{id:'file_test'}},base,async()=>({id:'file_test',url:null,upload_status:'processing'}));
assert.equal(g.status,'resolving');assert.equal(g.url,undefined);assert.ok(pendingMedia(g));
g=await resolveMedia({id:'media_test',status:'completed',file:{id:'file_test'}},base,async()=>{throw Error('temporary');});
assert.equal(g.status,'resolving');assert.equal(g.id,'media_test');
g=await resolveMedia({id:'media_test',status:'queued'},base,file);assert.ok(pendingMedia(g));
g=await resolveMedia({id:'media_test',status:'failed',error:{message:'Provider refused'}},base,file);assert.equal(g.status,'failed');assert.equal(g.error,'Provider refused');
g=await resolveMedia({id:'media_test',status:'completed',file:{url:'https://example.com/poster.svg',content_type:'image/svg+xml'}},base,file);assert.equal(g.status,'failed');assert.equal(g.url,undefined);
g=await resolveMedia({id:'media_test',status:'completed',file:{url:'javascript:alert(1)'}},base,file);assert.equal(g.status,'failed');
await assert.rejects(resolveMedia({},base,file),/no media ID/);
const input={type:'video',prompt:'  Test  ',duration:'5',resolution:'1080p',demo:false,accountId:'biz_test',requestKey:'same-key'};
const args=mediaArgs(input);assert.ok(!args.includes('--wait'));assert.equal(args[args.indexOf('--idempotency-key')+1],'same-key');assert.deepEqual(args,mediaArgs(input));assert.ok(args.includes('biz_test'));assert.ok(!mediaArgs({...input,type:'image'}).includes('--resolution'));
const referenceArgs=mediaArgs({...input,referenceIds:['file_one','file_two']});
assert.deepEqual(JSON.parse(referenceArgs[referenceArgs.indexOf('--reference_media')+1]),['file_one','file_two']);
assert.ok(!mediaArgs({...input,referenceIds:[]}).includes('--reference_media'));
const manyRefs=mediaArgs({...input,referenceIds:['a','b','c','d','e']});
assert.equal(JSON.parse(manyRefs[manyRefs.indexOf('--reference_media')+1]).length,4);
for(const type of ['image','video']) {
 const generated=demoResolve(['media','generate','--type',type,'--prompt','test']);
 const refreshed=demoResolve(['media','get',generated.id]);
 assert.equal(generated.type,type);assert.equal(refreshed.type,type);assert.equal(generated.file.url,refreshed.file.url);assert.ok(generated.file.content_type.startsWith(type+'/'));assert.equal(generated.cost,'0.00');
}
const probe=JSON.parse(execFileSync('ffprobe',['-v','error','-show_entries','stream=codec_name,width,height','-show_entries','format=duration','-of','json','public/demo/studio-sample.mp4'],{encoding:'utf8'}));
assert.equal(probe.streams[0].codec_name,'h264');assert.equal(Number(probe.format.duration),5);
execFileSync('ffmpeg',['-v','error','-i','public/demo/studio-sample.mp4','-f','null','-']);
console.log('Media checks passed: file resolution, delayed readiness, failures, wrong types, envelopes, idempotency, sample refresh, and 5s H.264 decode.');
const {generationBrief,EMPTY_CONTEXT,validDestination}=await load('src/lib/studio-context.ts');
assert.ok(generationBrief('Show the community',{...EMPTY_CONTEXT,format:'story'}).includes('vertical 9:16'));
assert.ok(generationBrief('x'.repeat(2000),EMPTY_CONTEXT).length<=2000);
assert.equal(validDestination('javascript:alert(1)'),false);
assert.equal(validDestination('https://whop.com/example'),true);
const {renderCreative,DEFAULT_FINISH}=await load('src/lib/studio-canvas.ts');
let draw=[];
const ctx={drawImage:(...args)=>{draw=args;},measureText:()=>({width:0})};
const canvas={width:0,height:0,getContext:()=>ctx};
const source={naturalWidth:2000,naturalHeight:1000};
renderCreative(canvas,source,{...DEFAULT_FINISH,format:'square',offsetX:0});
assert.equal(canvas.width,1080);assert.equal(canvas.height,1080);assert.ok(draw[1]===0);
renderCreative(canvas,source,{...DEFAULT_FINISH,format:'square',offsetX:100});
assert.equal(draw[1],-1080);assert.equal(draw[3],2160);
console.log('Studio workflow checks passed: destination validation, prompt length/placement and crop positioning.');
